koyel/config/routes.rb
Koyel::Application.routes.draw do

  root :to => 'users#index'
  resources :users do
   resources :posts
  end

end

koyel/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to:user
  attr_accessible :title, :description
end

koyel/app/models/user.rb
class User < ActiveRecord::Base
  before_save :abc
  protected
  def abc
  if firstname.nil? 
   firstname=email
   lastname=nil
  end
  end
  validates :email, :presence => true
  before_create do |user|
   user.firstname=user.firstname.capitalize
   user.lastname=user.lastname.capitalize
  end
  
attr_accessible :firstname, :email, :department, :age, :contactno, :gender, :country, :lastname
  has_many:posts
end

koyel/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

koyel/app/controllers/posts_controller.rb
class PostsController < ApplicationController
 def new
  @user=User.find(params[:user_id])
  @post=@user.posts.new
 end
 def create
  @user=User.find(params[:user_id])
  @post=@user.posts.create(params[:post])
  @post.save!
  redirect_to user_path(@user)
 end
 def edit
  @user=User.find(params[:user_id])
  @post=@user.posts.find(params[:id])
 end
 def update
  user=User.find(params[:user_id])
  post=user.posts.find(params[:id])
  post.update_attributes(params[:post])
  post.save!
  redirect_to user_path(user)
 end
 def show
  @user=User.find(params[:user_id])
  @post=@user.posts.find(params(:id))
 end
 def destroy
  @user=User.find(params[:user_id])
  @post=@user.posts.find(params[:id])
  @post.destroy
  redirect_to user_path(@user)
 end
end

koyel/app/controllers/users_controller.rb
class UsersController < ApplicationController
 def index
  @users=User.all
 end
 def new
  @user=User.new
 end
 def create
  @user=User.create(params[:user])
  @user.save!
  UserMailer.welcome_email(@user).deliver
  redirect_to users_path
 end
 def show
  @user=User.find(params[:id])
 end
 def destroy
  @user=User.find(params[:id])
  @user.destroy
  redirect_to users_path
 end
 def edit
  @user=User.find(params[:id])
 end
 def update
  user=User.find(params[:id])
  user.update_attributes(params[:user])
  user.save!
  redirect_to users_path
 end
end

koyel/app/helpers/application_helper.rb
module ApplicationHelper
end

koyel/app/helpers/posts_helper.rb
module PostsHelper
end

koyel/app/helpers/users_helper.rb
module UsersHelper
end

koyel/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Koyel</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

koyel/app/views/posts/edit.html.erb
<h3>Editing Post</h3>
<%= form_for @post,:url =>user_post_path do |a|%>
<p>
<%= a.label:title%><br/>
<%= a.text_field:title%>
</p>
<p>
<%= a.label:description%><br/>
<%= a.text_area:description%>
</p>
<%= a.submit%>
<%end%>
<p>
<%= link_to "Back", user_path(@user)%>
</p>

koyel/app/views/posts/new.html.erb
<h3>Create New Post</h3>
<%= form_for @post,:url=>user_posts_path do |a|%>
<p>
<%= a.label:title%><br/>
<%= a.text_field:title%>
</p>
<p>
<%= a.label:description%><br/>
<%= a.text_area:description%>
</p>
<%= a.submit%>
<%end%>
<p>
<%= link_to "Back", user_path(@user)%>
</p>

koyel/app/views/posts/show.html.erb
<%= @post.title%>
<%= @post.description%>
<%= link_to "Edit", edit_user_post_path(@post)%>
<%= link_to "Back", user_path(@user)%>

koyel/app/views/users/edit.html.erb
<h2>Editing User</h2>
<%= form_for @user do |b|%>
<div>
<%= b.label:firstname%><br/>
<%= b.text_field:firstname%>
</div>
<div>
<%= b.label:lastname%><br/>
<%= b.text_field:lastname%>
</div>
<div>
<%= b.label:email%><br/>
<%= b.text_field:email%>
</div>
<div>
<%= b.label:age%><br/>
<%= b.text_field:age%>
</div>
<div>
<%= b.label:contactno%><br/>
<%= b.text_field:contactno%>
</div>
<div>
<%= b.label:gender%><br/>
<%= b.text_field:gender%>
</div>
<div>
<%= b.label:country%><br/>
<%= b.text_field:country%>
</div>
<%=b.submit%>
<%end%>
<%=link_to "Show", user_path(@user)%>&nbsp|
<%=link_to "Back", users_path%>

koyel/app/views/users/index.html.erb
<h1>User's List</h1>
<table>
<tr>
<th>Name</th>
<th>Email</th>
<th> </th>
<th> </th>
<th> </th>
</tr>
<% @users.each do |user| %>
<tr>
<td>&nbsp<%=user.firstname %>
<%= user.lastname%>&nbsp&nbsp&nbsp</td>
<td>&nbsp&nbsp<%=user.email %>&nbsp&nbsp&nbsp</td>
<td><%=link_to "Show", user_path(user)%>&nbsp&nbsp&nbsp</td>
<td><%= link_to "Edit", edit_user_path(user)%>&nbsp&nbsp&nbsp</td>
<td><%= link_to "Destroy", user_path(user),:confirm => 'Are you sure?', :method => :delete %></td>
</tr>
<%end%>
</table>
<br />
<%=link_to "Create User",new_user_path%>

koyel/app/views/users/new.html.erb
<h2>Create New User</h2>
<%= form_for @user do |f|%>
<div>
<%= f.label:firstname%><br/>
<%= f.text_field:firstname%>
</div>
<div>
<%= f.label:lastname%><br/>
<%= f.text_field:lastname%>
</div>
<div>
<%= f.label:email%><br/>
<%= f.text_field:email%>
</div>
<div>
<%= f.label:age%><br/>
<%= f.text_field:age%>
</div>
<div>
<%= f.label:contactno%><br/>
<%= f.text_field:contactno%>
</div>
<div>
<%= f.label:gender%><br/>
<%= f.text_field:gender%>
</div>
<div>
<%= f.label:country%><br/>
<%= f.text_field:country%>
</div>
<%= f.submit%>
<%end%>
<%= link_to "Back", users_path%>

koyel/app/views/users/show.html.erb
<h2>My details:</h2>
<p>
<b>Name:</b>
<%=@user.firstname%>
<%=@user.lastname%>
</p>
<p>
<b>Email id:</b>
<%=@user.email%>
</p>
<p>
<b>Age:</b>
<%=@user.age%>
</p>
<p>
<b>Contact No:</b>
<%=@user.contactno%>
</p>
<p>
<b>Gender:</b>
<%=@user.gender%>
</p>
<p>
<b>Country:</b>
<%=@user.country%>
</p>
<%= link_to "Edit", edit_user_path(@user)%>&nbsp||
<%= link_to "Back", users_path%>
<h2>My Posts::------</h2>
<%@user.posts.each do |post|%>
<p>
<b>Title:</b>
<%=post.title%>
</p>
<p>
<b>Description:</b>
<%=post.description%>
</p>
<%= link_to "Edit Post",edit_user_post_path(post.user,post)%>&nbsp|
<%= link_to "Destroy Post", [post.user,post],:confirm => 'Are you sure', :method => :delete%><br/>
<%end%>
<p>
<%= link_to "Create New Post", new_user_post_path(@user)%>
</p>